[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory to publish (relative to root of your repo)
  publish = "web"
  
  # Default build command
  command = ""
  
  # Functions directory
  functions = "netlify/functions"

# Redirects for SPA routing (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling
[build.processing]
  skip_processing = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache control for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 