[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory to publish (relative to root of your repo)
  publish = "web"
  
  # Default build command
  command = ""
  
  # Functions directory
  functions = "netlify/functions"

# Function redirects (must come before catch-all)
[[redirects]]
  from = "/download-guide"
  to = "/.netlify/functions/download-guide"
  status = 200
  force = true

[[redirects]]
  from = "/newsletter"
  to = "/.netlify/functions/newsletter"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true

[[redirects]]
  from = "/question-details/*"
  to = "/.netlify/functions/question-details"
  status = 200
  force = true

[[redirects]]
  from = "/service-details/*"
  to = "/.netlify/functions/service-details"
  status = 200
  force = true

[[redirects]]
  from = "/stat-detail/*"
  to = "/.netlify/functions/stat-detail"
  status = 200
  force = true

[[redirects]]
  from = "/quick-book"
  to = "/.netlify/functions/quick-book"
  status = 200
  force = true

[[redirects]]
  from = "/contact-form-fields"
  to = "/.netlify/functions/contact-form-fields"
  status = 200
  force = true

[[redirects]]
  from = "/store-lead"
  to = "/.netlify/functions/store-lead"
  status = 200
  force = true

[[redirects]]
  from = "/admin/leads"
  to = "/.netlify/functions/view-leads"
  status = 200
  force = true

# Catch-all redirect for SPA routing (must come last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling
[build.processing]
  skip_processing = false

# Install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache control for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 